Sc 30945/client dmi partners inc pulled an export
activeprospect/leadconduit-types pull request #130
Opened 2021-11-05 15:00 UTC by richardfordjunior

## Description of the change

> This fixes the issue where rich-types are not being properly masked in exports

## Type of change
- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

> https://app.shortcut.com/active-prospect/story/30945/client-dmi-partners-inc-pulled-an-export-of-tf-data-service-info-for-leads-even-though-the-certs-are-not-masked-many-of-the

## Checklists

### Development and Testing

- [X]  Lint rules pass locally.
- [X]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [X]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [X]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [X]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [X]  This branch has been rebased off master to be current.

### Tracking 
- [X]  Issue from Clubhouse has a link to this pull request.
- [X]  This PR has a link to the issue in Clubhouse.

### QA
- [ ]  This branch has been deployed to staging and tested.

2021-11-08 17:47 UTC, asedarski submitted a review, later dismissed

2021-11-09 16:26 UTC, mikebetts requested changes
Looks like this covers masking rich types in general, but it seems like this still isn't handling the case where the masked property itself is a rich type. It is supposed to look at its boolean value to determine whether to mask or not.

2021-11-09 16:26 UTC, mikebetts commented on lib/index.js
> +        obj[key] = mask(value, (obj.masked != null || obj.masked !== undefined) || doMask);
I'm confused by this - if `obj.masked` is an object, won't it always return true and therefore mask despite what the masked value is set to in that object?

2021-11-09 16:32 UTC, richardfordjunior commented on lib/index.js
> +        obj[key] = mask(value, (obj.masked != null || obj.masked !== undefined) || doMask);
I see what you mean. I'll update to cover when the `obj.masked` is a rich type.

2021-11-09 16:41 UTC, richardfordjunior commented on lib/index.js
> +        obj[key] = mask(value, (obj.masked != null || obj.masked !== undefined) || doMask);
Yes.

2021-11-30 15:54 UTC, asedarski approved these changes
Provided the assertions in the tests are correct (I don't understand the business logic behind what's masked and what isn't), LGTM

2021-12-01 15:05 UTC, closed without merging