TrustedForm URL
activeprospect/leadconduit-types pull request #135
Opened 2022-03-18 00:36 UTC by alexkwolfe

## Description of the change

This adds a new data type called `trustedform_url`. The `trustedform_cert_url` should be converted to this type. In production, one or two customers are using the `host` and `path` components, so I've left those. All the other components of the `url` type are not necessary.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

[Shortcut #37783](https://app.shortcut.com/active-prospect/story/37783/trustedform-cert-url-type)

## Checklists

### Development and Testing

- [ ]  Lint rules pass locally.
- [ ]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2022-03-18 17:08 UTC, cgrayson requested changes
Nice. A couple minor things inline, plus you can delete `package-lock.json`. It's ignored for anything but the top-level package being installed, and so is omitted from dependent libraries like this one. (Also, icymi: we can't "approve" PRs & let the author fix & merge anymore; after you make changes, this review will be stale and you'll have to re-request another one.)

2022-03-18 17:08 UTC, cgrayson commented on test/trustedform-url.test.js
> +// these environment variables must be set before requiring the type
Hmm. Does this mean that LC won't launch without having values for these?

2022-03-22 16:23 UTC, alexkwolfe commented on test/trustedform-url.test.js
> +// these environment variables must be set before requiring the type
LC will launch, but the type won't parse TF URLs because the private keys won't be set.

2022-03-23 12:32 UTC, cgrayson approved these changes
LGTM

2022-03-23 20:47 UTC, merged