add dob type
activeprospect/leadconduit-types pull request #149
Opened 2022-08-11 21:37 UTC by jgrayson676

## Description of the change

Adds a new `dob` type and fixes a bug with the tf cert url tests.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

https://app.shortcut.com/active-prospect/story/40321/user-maps-dob-components

## Checklists

### Development and Testing

- [ ]  Lint rules pass locally.
- [ ]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2022-08-11 21:39 UTC, jgrayson676 commented on lib/types/dob.js
> +  maskable: false,
Additional changes will be needed to support partial masking of this field, so I've left it unmasked until those changes are made.

2022-08-12 14:29 UTC, josevsalina commented on test/dob.test.js
> +        assert.equal(dob.parse(string).age, 8);
In this case, the age should be 7 instead? he has 7 years and 11 months

2022-08-12 14:33 UTC, josevsalina commented on test/dob.test.js
> +        assert.equal(dob.parse(string).age, 7.9);
and in this case is 7 years and 10 months, not sure what the .9 means

2022-08-12 14:45 UTC, richardfordjunior commented on lib/types/dob.js
> +const moment = require('moment');
Can we use another utility, since moment is deprecated?

2022-08-12 15:15 UTC, johnrb2 requested changes
Great work, just a couple of changes requested and some questions.

2022-08-12 15:15 UTC, johnrb2 commented on test/trustedform-url.test.js
>  const moment = require('moment');
```suggestion
const {assert} = require('chai');
```
moment library is unused can be removed

2022-08-12 15:15 UTC, johnrb2 commented on lib/types/dob.js
> +  // parsed.masked = false;
Is this a comment for once masking is added?

2022-08-12 15:15 UTC, johnrb2 commented on test/dob.test.js
> +      });
How do we feel about only keeping the tests that don't have overlap with the Date type?

2022-08-12 16:21 UTC, cgrayson approved these changes
Otherwise LGTM

2022-08-12 16:21 UTC, cgrayson commented on test/dob.test.js
> +        assert.equal(dob.parse(string).age, 7.9);
See above; the difference to 6/18/22 is 7 years, 11 months. And the story called for a decimal representation of the number of years. So roughly estimating by months: 7 + 11/12 = 7.9 (though the calculation is actually based on number of days.)

2022-08-12 16:21 UTC, cgrayson commented on lib/types/dob.js
> +const moment = require('moment');
@richardfordjunior - personally I think that kind of change is worth its own story, and moment would be replaced throughout the library all at once. Also - if there's a chosen replacement for usage in LC libraries, I don't know what it is. If not, I also think that's worth some deliberation and standardization on that. My 2¢.

2022-08-15 18:56 UTC, johnrb2 approved these changes
LGTM!

2022-08-15 19:03 UTC, johnrb2 commented
It looks like the Date test is choking on the last string in `euroStrings` array. Also not sure if we want to change L9 of `.github/workflows/test.yml` to

```yml
        node-version: [14.x, 16.x]
```

since we are on Node 14 going to 16

2022-08-15 19:13 UTC, johnrb2 commented
If you change the `lib/types/date.js` if you replace the array starting on [L9](https://github.com/activeprospect/leadconduit-types/blob/9ecae0a012d40e28abb94e32acbd4073f9d1c75c/lib/types/date.js#L9) to 

`fixes comment on L17 and adds format to L28`
```js
const formats = [
  'ddd MMM DD YYYY', // 'Mon Jun 02 2014'
  'MMM DD YYYY',     // 'Jun 02 2014'
  'M/D/YYYY',        // '6/2/2014', '06/02/2014'
  'M/D/YY',          // '6/2/14'
  'YYYY-MM-DD',      // '2014-06-02'
  'MM-DD-YYYY',      // '06-02-2014'
  'MMDDYYYY',        // '06022014'
  'YYYYMMDD',        // '20140602'

  // European formats (month first)
  'ddd DD MMM YYYY',   // 'Fri 18 July 2014'
  'DD MMM YYYY',       // '18 July 2014'
  'D/M/YYYY',          // '18/7/2014'
  'D/M/YY',            // '18/7/14'
  'YYYY-DD-MM',        // '2014-18-07'
  'DD-MM-YYYY',        // '18-07-2014'
  'DDMMYYYY',          // '18072014'
  'YYYY-DD-MM',        // '2014-18-07'
  'YYYYDDMM'           // '20141807'
];
```

2022-08-15 19:28 UTC, johnrb2 submitted a review, later dismissed
Nice!

2022-08-22 14:48 UTC, asedarski submitted a review, later dismissed

2022-08-22 15:20 UTC, richardfordjunior submitted a review, later dismissed
Nice work, LGTM

2022-09-01 15:57 UTC, cgrayson approved these changes

2022-09-01 15:58 UTC, merged

2022-09-01 16:00 UTC, robdll approved these changes