Sc 50139/super admin can export leads with full dob
activeprospect/leadconduit-types pull request #157
Opened 2023-05-05 21:19 UTC by johnrb2

## Description of the change
<pre>
remove dob masking (index.js)
set dob.maskable to false (which triggers data-masking in lib/handler/middleware/source.js)
leave dob.parsed.masked (which triggers masking in requests via leadconduit-mask)
add function getHideableType(field)
   needed because event data from db doesn't have explicit type info
   returns "dob" if field has age & year attributes
   return null otherwise
add function shouldHide(field)
   returns boolean based on call to getHideableType() being null or not
add function hide(field)
  calls getHideableType(field)
  if result is not null, mask raw & normal based on type (e.g., "dob")
</pre>

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

> https://app.shortcut.com/active-prospect/story/50139/super-admin-can-export-leads-with-full-dob

## Checklists

### Development and Testing

- [ ]  Lint rules pass locally.
- [ ]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut/Jira has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2023-05-09 21:15 UTC, jgrayson676 submitted a review, later dismissed

2023-05-10 17:29 UTC, samullen approved these changes

2023-05-12 12:35 UTC, samullen commented on lib/index.js
> +  };
Would it makes sense to extract the logic from the if/else into functions so it's more understandable about what's going on?

Example:

```
if (isSpecialObject) {
  maskString(str);
}
else {
  maskObject(obj);
}

2023-05-12 12:35 UTC, samullen commented on lib/index.js
>    return obj;
This also seems like something we'd want to extract into its own function to make `mask` more understandable and testable.

2023-05-12 16:56 UTC, johnrb2 commented on lib/index.js
>    return obj;
I'll take a look and see if I can't improve readability and reduce complexity.

2023-05-12 19:03 UTC, cgrayson requested changes
A few questions, & I think it's worth adding more test coverage

2023-05-15 00:11 UTC, johnrb2 commented on lib/index.js
> +    str.masked = true;
It needs to be converted to a String object so that the front end doesn't try to use the Date methods.

2023-05-15 00:12 UTC, johnrb2 commented on test/index.test.js
> +    const normalizedDob = index.normalize(dob.parse('01-01-2000'));
The hide function is dealing with lead properties after they have been normalized going into the database.

2023-05-17 16:07 UTC, johnrb2 commented on lib/index.js
> +    if ((obj.masked === false) && (obj instanceof String || obj instanceof Boolean || obj instanceof Number || obj instanceof Date)) {
I have decided to bump changes to this logic to another story. To facilitate getting this out while we work out complexities involved with masking or not masking Dates

2023-05-17 16:08 UTC, johnrb2 commented
I have decided to bump questions and optimizations about the mask function to another story so that we can get this functionality out

2023-05-17 16:09 UTC, johnrb2 commented
Reductions in coverage have to do with Date object not being tested in the mask function due to removing the dob checks

2023-05-17 16:10 UTC, johnrb2 commented on lib/index.js
> +    str.masked = true;
It will throw a type error as described in our slack conversation attached to the other story

2023-05-17 19:07 UTC, cgrayson approved these changes

2023-05-19 14:06 UTC, josevsalina commented on lib/index.js
> +    if ((obj.masked === false) && (obj instanceof String || obj instanceof Boolean || obj instanceof Number || obj instanceof Date)) {
If obj is number and you run a `.toString` it will not be a date, will it?

2023-05-19 14:29 UTC, johnrb2 commented on lib/index.js
> +    if ((obj.masked === false) && (obj instanceof String || obj instanceof Boolean || obj instanceof Number || obj instanceof Date)) {
No, it will not.

Here is a quick little script to test:

```js
const num = new Number(123);
const numStr = num.toString();
console.log(num); // [Number: 123]
console.log(typeof num); // object
console.log(typeof numStr); // string
console.log(num instanceof Number); // true
console.log(numStr instanceof Date); // false

const num2 = 123;
const num2Str = num2.toString();
console.log(num2); // 123
console.log(typeof num2); // number
console.log(typeof num2Str); // string
console.log(num2 instanceof Number); // false
console.log(num2Str instanceof Date); // false
```

2023-05-19 15:44 UTC, josevsalina approved these changes
LGTM

2023-05-19 16:00 UTC, merged